package com.ftn.sbnz.rules.validacija;

import com.ftn.sbnz.model.KreditniZahtev;
import com.ftn.sbnz.model.Status;

rule "Validacija zahteva - osnovni podaci"
when                   //filter, validiram samo UNOS
    $z: KreditniZahtev(status == Status.UNOS, klijent != null, iznos > 0) //variable binding, tj nadimak za objekat KreditniZahtev
then
    System.out.println("Validacija: Podaci su ispravni.");
    $z.setStatus(Status.VALIDIRANO);
    update($z); //obavezno obavestiti engine o promeni
end