package com.ftn.sbnz.rules.klasifikacija;

import com.ftn.sbnz.model.KreditniZahtev;
import com.ftn.sbnz.model.Klijent;
import com.ftn.sbnz.model.Status;
import com.ftn.sbnz.model.KreditniRazred;
import com.ftn.sbnz.model.KreditnaIstorija;

rule "Klasifikacija - Odobren Razred A"
    salience -200
when
    $z: KreditniZahtev(status == Status.IZRACUNAT_DTI, dti < 0.3)
    $k: Klijent(kreditnaIstorija == KreditnaIstorija.ODLICNA, slobodanPrihod >= 0.3) from $z.getKlijent()
then
    System.out.println("Pravilo: Odobren kredit - Razred A.");
    modify($z) {
        setRazred(KreditniRazred.A),
        setStatus(Status.ODOBREN),
        setObrazlozenje("Odobreno: Odlicna kreditna istorija i nizak DTI (Razred A).")
    }
end

rule "Klasifikacija - Odobren Razred B"
    salience -200
when
    $z: KreditniZahtev(status == Status.IZRACUNAT_DTI, dti < 0.4)
    $k: Klijent(kreditnaIstorija == KreditnaIstorija.DOBRA, slobodanPrihod >= 0.25) from $z.getKlijent()
then
    System.out.println("Pravilo: Odobren kredit - Razred B.");
    modify($z) {
        setRazred(KreditniRazred.B),
        setStatus(Status.ODOBREN),
        setObrazlozenje("Odobreno: Dobra kreditna istorija i stabilan DTI (Razred B).")
    }
end

rule "Klasifikacija - Odobren Razred C"
    salience -200
when
    $z: KreditniZahtev(status == Status.IZRACUNAT_DTI, dti < 0.5)
    $k: Klijent(kreditnaIstorija == KreditnaIstorija.LOSA) from $z.getKlijent()
then
    System.out.println("Pravilo: Odobren kredit - Razred C.");
    modify($z) {
        setRazred(KreditniRazred.C),
        setStatus(Status.ODOBREN),
        setObrazlozenje("Odobreno: Kredit odobren uz visi rizik (Razred C).")
    }
end

rule "Klasifikacija - Odbijen Razred D"
    salience -200
when
    $z: KreditniZahtev(status == Status.IZRACUNAT_DTI)
    $k: Klijent(kreditnaIstorija == KreditnaIstorija.NEPRIHVATLJIVA) from $z.getKlijent()
    eval($z.getDti() >= 0.5 || !$z.isKolateralPostoji())
then
    System.out.println("Pravilo: Odbijen kredit - Razred D.");
    modify($z) {
        setRazred(KreditniRazred.D),
        setStatus(Status.ODBIJEN),
        setObrazlozenje("Odbijeno: Neprihvatljiva istorija ili previsok DTI bez kolaterala (Razred D).")
    }
end

rule "Klasifikacija - Odbijen Razred E (Stecaj)"
    salience -200
when
    $z: KreditniZahtev(status == Status.IZRACUNAT_DTI)
    $k: Klijent(imaStecajIliNaplatuU12Meseci() == true) from $z.getKlijent()
then
    System.out.println("Pravilo: Odbijen kredit - Razred E (Stecaj/Naplata).");
    modify($z) {
        setRazred(KreditniRazred.E),
        setStatus(Status.ODBIJEN),
        setObrazlozenje("Odbijeno: Registrovan stecaj ili prinudna naplata u poslednjih 12 meseci (Razred E).")
    }
end